import type { Challenge } from "./store"

export const initialChallenges: Challenge[] = [
  {
    id: "1",
    title: "Digital Sunset",
    description: "Take a photo of your evening activity that doesn't involve screens, 30 minutes before bed.",
    category: "Wellness",
    difficulty: "Medium",
    hashtag: "#DigitalSunset",
    quote: "Being present is the greatest gift you can give to yourself.",
    author: "Mo Abudu, Nigerian Media Executive",
    scheduledDate: "2025-04-04",
  },
  {
    id: "2",
    title: "Window Gazing",
    description:
      "Spend 5 minutes looking out of a window and capture a photo of the view with your thoughts as the caption.",
    category: "Mindfulness",
    difficulty: "Easy",
    hashtag: "#DailyWindow",
    quote: "Look up at the world around you, not down at your phone.",
    author: "Olufemi Elias, Nigerian Philosopher",
    scheduledDate: "2025-04-05",
  },
  {
    id: "3",
    title: "Water First",
    description: "Take a creative photo of your morning glass of water before drinking it first thing in the morning.",
    category: "Wellness",
    difficulty: "Easy",
    hashtag: "#DailyHydrate",
    quote: "The simplest habits often have the most profound effects.",
    author: "Jimi Famurewa, Nigerian Health Advocate",
    scheduledDate: "2025-05-01",
  },
  {
    id: "4",
    title: "One-Song Dance",
    description: "Record a short clip of yourself dancing to your favorite song - even if it's just for a few seconds!",
    category: "Wellness",
    difficulty: "Easy",
    hashtag: "#DailyDance",
    quote: "Dance is the hidden language of the soul.",
    author: "Kaffy, Nigerian Dancer & Choreographer",
    scheduledDate: "2025-05-02",
  },
  {
    id: "5",
    title: "Local Snack",
    description: "Try a local snack from a small vendor and share a photo or short review video of your experience.",
    category: "Food",
    difficulty: "Easy",
    hashtag: "#LocalTaste",
    quote: "The best way to experience a culture is through its everyday food.",
    author: "Chef Fregz, Nigerian Chef",
    scheduledDate: "2025-05-03",
  },
  {
    id: "6",
    title: "Sunset Moment",
    description:
      "Capture a photo of today's sunset from wherever you are - no filters needed, just the natural beauty.",
    category: "Mindfulness",
    difficulty: "Easy",
    hashtag: "#DailySunset",
    quote: "Every sunset brings the promise of a new dawn.",
    author: "Wole Soyinka, Nobel Laureate",
    scheduledDate: "2025-05-04",
  },
  {
    id: "7",
    title: "New Word",
    description: "Learn one new word and create a creative photo or video that represents its meaning.",
    category: "Learning",
    difficulty: "Easy",
    hashtag: "#DailyWord",
    quote: "Language connects us to our heritage and to each other.",
    author: "Adichie, Nigerian Author",
    scheduledDate: "2025-05-05",
  },
  {
    id: "8",
    title: "Morning Pages",
    description: "Share a photo of your 3-minute morning writing, with one sentence that stands out to you.",
    category: "Creativity",
    difficulty: "Easy",
    hashtag: "#MorningThoughts",
    quote: "Write without fear, edit without mercy.",
    author: "Chimamanda Ngozi Adichie, Nigerian Author",
    scheduledDate: "2025-06-01",
  },
  {
    id: "9",
    title: "Phone-Free Hour",
    description: "Take a before and after selfie of your phone-free hour, sharing what you did instead.",
    category: "Wellness",
    difficulty: "Medium",
    hashtag: "#DigitalBreak",
    quote: "Almost everything will work again if you unplug it for a few minutes, including you.",
    author: "Bankole Wellington, Nigerian Artist & Entrepreneur",
    scheduledDate: "2025-06-02",
  },
  {
    id: "10",
    title: "Sky Watching",
    description:
      "Spend 3 minutes looking up at the sky and capture a photo of what you see - clouds, stars, or colors.",
    category: "Mindfulness",
    difficulty: "Easy",
    hashtag: "#LookUp",
    quote: "The sky is the daily bread of the eyes.",
    author: "John Lubbock, Naturalist",
    scheduledDate: "2025-06-03",
  },
  {
    id: "11",
    title: "New Song",
    description:
      "Listen to one song from a genre you don't usually listen to and share a short reaction video or photo.",
    category: "Arts",
    difficulty: "Easy",
    hashtag: "#NewSound",
    quote: "Music gives a soul to the universe, wings to the mind.",
    author: "Fela Kuti, Nigerian Musician",
    scheduledDate: "2025-06-04",
  },
  {
    id: "12",
    title: "Compliment Someone",
    description:
      "Give a genuine compliment to someone and capture their reaction (with permission) or your reflection on how it felt.",
    category: "Social",
    difficulty: "Easy",
    hashtag: "#SpreadJoy",
    quote: "Your words have power. Use them to lift others up.",
    author: "Peter Drucker, Management Consultant",
    scheduledDate: "2025-06-05",
  },
  {
    id: "13",
    title: "Market Visit",
    description: "Visit a local market and capture a photo of the most colorful stall or interesting vendor you find.",
    category: "Adventure",
    difficulty: "Medium",
    hashtag: "#LocalMarket",
    quote: "Markets are the heartbeat of our communities.",
    author: "Mosunmola Abudu, Nigerian Entrepreneur",
    scheduledDate: "2025-06-06",
  },
  {
    id: "14",
    title: "Morning Light",
    description: "Capture the first light of morning through your window or from your balcony.",
    category: "Photography",
    difficulty: "Easy",
    hashtag: "#MorningGlow",
    quote: "Each morning we are born again. What we do today is what matters most.",
    author: "Tara Durotoye, Nigerian Entrepreneur",
    scheduledDate: "2025-06-07",
  },
  {
    id: "15",
    title: "Street Art",
    description:
      "Find and photograph an interesting piece of street art, graffiti, or public art in your neighborhood.",
    category: "Arts",
    difficulty: "Medium",
    hashtag: "#StreetCanvas",
    quote: "Art should comfort the disturbed and disturb the comfortable.",
    author: "Victor Ehikhamenor, Nigerian Artist",
    scheduledDate: "2025-06-08",
  },
  {
    id: "16",
    title: "Gratitude Moment",
    description: "Write down three things you're grateful for today and take a photo that represents one of them.",
    category: "Mindfulness",
    difficulty: "Easy",
    hashtag: "#DailyGratitude",
    quote: "Gratitude turns what we have into enough.",
    author: "Ibukun Awosika, Nigerian Businesswoman",
    scheduledDate: "2025-06-09",
  },
  {
    id: "17",
    title: "Random Act of Kindness",
    description: "Perform a small act of kindness for someone and share what you did (without showing the recipient).",
    category: "Social",
    difficulty: "Easy",
    hashtag: "#KindnessMatters",
    quote: "No act of kindness, no matter how small, is ever wasted.",
    author: "Aesop, Ancient Storyteller",
    scheduledDate: "2025-06-10",
  },
  {
    id: "18",
    title: "Book Page",
    description: "Share a photo of a page from a book you're reading with your favorite line highlighted.",
    category: "Learning",
    difficulty: "Easy",
    hashtag: "#PageTurn",
    quote: "Reading is to the mind what exercise is to the body.",
    author: "Lola Shoneyin, Nigerian Author",
    scheduledDate: "2025-06-11",
  },
  {
    id: "19",
    title: "Nature Touch",
    description: "Find something natural (a leaf, stone, flower) and take a close-up photo of it in your hand.",
    category: "Mindfulness",
    difficulty: "Easy",
    hashtag: "#NatureConnect",
    quote: "In nature, nothing is perfect and everything is perfect.",
    author: "Newton Jibunoh, Nigerian Environmentalist",
    scheduledDate: "2025-06-12",
  },
  {
    id: "20",
    title: "Five Minute Meditation",
    description: "Take a before and after selfie of a five-minute meditation session, noting how you feel in each.",
    category: "Wellness",
    difficulty: "Medium",
    hashtag: "#MindfulMoment",
    quote: "The present moment is the only time over which we have dominion.",
    author: "Toke Makinwa, Nigerian Media Personality",
    scheduledDate: "2025-06-13",
  },
]
